# ADS1115 configuration - Two tanks (Fresh Water + Grey Water)
i2c:
  bus: 1
  address: 0x48
  reference_voltage: 3.3  # Volts

# Sensors configuration - Two tank setup
sensors:
  - type: tank
    name: "Fresh Water Tank"
    channel: 0
    fixed_resistor: 220    # Ohms (voltage divider)
    sensor_min: 0.1       # Ohms (Empty - RAW 12)
    sensor_max: 13.55     # Ohms (Full - RAW 1532)
    tank_capacity: 0.07   # Cubic Meters (0.07 m3 = 70 Liters)
    fluid_type: fresh_water  #fresh_water, waste_water, fuel, oil, etc.
    update_interval: 5000  # milliseconds

  - type: tank
    name: "Grey Water Tank"
    channel: 1
    fixed_resistor: 220    # Ohms (voltage divider)
    sensor_min: 0.1       # Ohms (Empty - RAW 12)
    sensor_max: 13.55     # Ohms (Full - RAW 1532)
    tank_capacity: 0.07   # Cubic Meters (0.07 m3 = 70 Liters)
    fluid_type: waste_water  #fresh_water, waste_water, fuel, oil, etc.
    update_interval: 5000  # milliseconds
